name: pull-request-check

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: make cmake g++ nlohmann-json3-dev libnl-genl-3-dev npm
          version: 1.0
      - run: make
        
